### ISSUE TITLE
ember-qunit beta.2 is causing issues with unregisterTextComponent

### ISSUE THREAD

**Issue by 0xadada** [poteto/ember-test-component#6]
Using `ember-test-component` with ember-qunit beta.2 is causing issues with `unregisterTextComponent`.

when unregisterTestComponent is invoked in the beforeEach hook, it passes testCtx.testEnvironment as an argument. unregisterTestComponent makes a call to getOwner:
https://github.com/poteto/ember-test-component/blob/00a156a3eec9c4bcc7096fb89cedb249ddb2a613/test-support/ember-test-component/index.js#L16

The owner is not resolved in ember-test-component when it tries to resolve registration of the component, because getOwner returns undefined, therefore owner is undefined.
https://github.com/poteto/ember-test-component/blob/00a156a3eec9c4bcc7096fb89cedb249ddb2a613/test-support/ember-test-component/index.js#L18

I'm working through the new unified testing RFC implementation with @rwjblue, and documented the problem in more detail here: 
https://github.com/emberjs/ember-qunit/issues/289

**Comment by rwjblue** [comment]
Basically, when ran under ember-qunit@3 (with [the new API](http://rwjblue.com/2017/10/23/ember-qunit-simplication/)) `getOwner(this)` is not going to return anything (the owner is directly on `this.owner`).

I submitted https://github.com/poteto/ember-test-component/pull/7 with a quick fix...
